BlogezyApp/Models/BlogezyDBContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogezyApp.Models
{
    public class BlogezyDBContext:DbContext
    {
        public BlogezyDBContext(DbContextOptions<BlogezyDBContext> options) :base(options) { }


        public DbSet<Post> Posts { get; set; }


        public DbSet<Comment> Comments { get; set; } 
    }
}

BlogezyApp/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BlogezyApp.Models
{
    public class Comment
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Text required")]
        [MaxLength(500)]
        public string Text { get; set; }

        [Required(ErrorMessage = "Post required")]
        public Post Post { get; set; }
         
        public int PostId { get; set; }
    }
}

BlogezyApp/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BlogezyApp.Models
{
    public class Post
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Title required")]
        [MaxLength(500)]
        public string Title { get; set; }

        [Required(ErrorMessage = "AddedDate required")] 
        public  DateTime  AddedDate { get; set; }
         

        public string Tag { get; set; }
         
        public ICollection<Comment> Comments { get; set; }

        [Required(ErrorMessage = "Image required")]
        public string Image { get; set; }

        [Required(ErrorMessage = "ShortDescription required")]
        public string ShortDescription { get; set; }

        [Required(ErrorMessage = "Details required")]
        public string Details { get; set; }
    }
}

BlogezyApp/Components/SideMenuViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BlogezyApp.ViewComponents
{
    [ViewComponent(Name = "SideMenu")]
    public class SideMenuViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return  View();
        }
    }
}

BlogezyApp/Controllers/DetailsPostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BlogezyApp.Models;
using Microsoft.EntityFrameworkCore;

namespace BlogezyApp.Controllers
{
    public class DetailsPostController : Controller
    {
        private BlogezyDBContext db;

        public DetailsPostController(DbContextOptions<BlogezyDBContext> options)
        {
          db = new BlogezyDBContext(options);
        }
       

        public IActionResult Index(int? id)
        {
            Post post = db.Posts.Find(id);
            post.Comments = db.Comments.Where(c => c.PostId == id).ToList();
            return View(post);
        }
    }
}

BlogezyApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlogezyApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BlogezyApp.Controllers
{
    public class HomeController : Controller
    {  
        private BlogezyDBContext db { get; }
         

        //public HomeController(DbContextOptions<BlogezyDBContext> options)
        //{
        //    db = new BlogezyDBContext(options);
        //}

        public HomeController(BlogezyDBContext blogezyDBContext)
        {
            db = blogezyDBContext;
            
        }

        public async Task<IActionResult> Index()
        {  
            List<Post> posts = await db.Posts.ToListAsync();
            List<Comment> comments = await db.Comments.ToListAsync();
            foreach (Post post in posts)
            {
                post.Comments = comments.Where(c => c.PostId == post.Id).ToList();
            }
            return View(posts);
        }
    }
}

BlogezyApp/Views/DetailsPost/Index.cshtml
@using BlogezyApp.Models;
@model Post;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-xl-12">  
        <article class="post">
            <div class="post-header">
                <h2 class="post-title"><a href="#">@Model.Title</a></h2>
                <ul class="post-meta">
                    <li><i class="mdi mdi-calendar"></i>@Model.AddedDate.ToString("dd/MM/yyyy")</li>
                    <li><i class="mdi mdi-tag-text-outline"></i> <a href="#">@Model.Tag</a></li>
                    <li><i class="mdi mdi-comment-multiple-outline"></i> <a href="#">@Model.Comments.ToList().Count Comments</a></li>
                </ul>
            </div>
            <div class="post-preview">
                <a href="#"><img src="~/images/blog/@Model.Image" alt="" class="img-fluid rounded"></a>
            </div>
            <div class="post-content">
                <p>@Model.Details</p>
            </div> 
        </article> 
</div> 

BlogezyApp/Views/Home/Index.cshtml
@using BlogezyApp.Models;
@model List<Post>;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-xl-8">
    @foreach (Post post in Model)
    {
        <!-- Post-->
        <article class="post">
            <div class="post-header">
                <h2 class="post-title"><a href="#">@post.Title</a></h2>
                <ul class="post-meta">
                    <li><i class="mdi mdi-calendar"></i>@post.AddedDate.ToString("dd/MM/yyyy")</li>
                    <li><i class="mdi mdi-tag-text-outline"></i> <a href="#">@post.Tag</a></li>
                    <li><i class="mdi mdi-comment-multiple-outline"></i> <a href="#">@post.Comments.ToList().Count Comments</a></li>
                </ul>
            </div>
            <div class="post-preview">
                <a href="#"><img src="~/images/blog/@post.Image" alt="" class="img-fluid rounded"></a>
            </div>
            <div class="post-content">
                <p>@post.ShortDescription...</p>
            </div>

            <div>
                <a href="@Url.Action("Index","DetailsPost", new { id = post.Id })" class="btn btn-outline-custom">Read More <i class="mdi mdi-arrow-right"></i></a>
            </div>
        </article>
        <!-- Post end-->
    }
    <!-- Pagination-->
    <div class="row">
        <div class="col-lg-12">
            <ul class="pagination">
                <li class="next"><a href="#"><i class="mdi mdi-chevron-left"></i></a></li>
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li class="prev"><a href="#"><i class="mdi mdi-chevron-right"></i></a></li>
            </ul>
        </div>
    </div>
    <!-- Pagination end-->
</div>


@await Component.InvokeAsync("SideMenu")

BlogezyApp/Views/Shared/Components/SideMenu/Default.cshtml
 <!-- Sidebar-->
<div class="col-xl-4">
    <div class="sidebar">

        <!-- Search widget-->
        <aside class="widget widget_search">
            <form>
                <input class="form-control pr-5" type="search" placeholder="Search...">
                <button class="search-button" type="submit"><span class="mdi mdi-magnify"></span></button>
            </form>
        </aside>

        <aside class="widget about-widget">
            <div class="widget-title">About Me</div>

            <div class="text-center">
                <img src="~/images/photo.jpg" alt="About Me" class="rounded-circle">

                <p>Quis vero phasellus hac nullam, in quam vitae duis adipiscing mauris leo, laoreet eget at quis, ante vestibulum vivamus vel. Sapien lobortis, eget orci purus amet pede, consectetur neque risus.</p>
            </div>

        </aside>

        <aside class="widget about-widget">
            <div class="widget-title">Subscribe & Follow</div>

            <ul class="socials">
                <li><a href="http://facebook.com"><i class="mdi mdi-facebook"></i></a></li>
                <li><a href="http://twitter.com"><i class="mdi mdi-twitter"></i></a></li>
                <li><a href="http://instagram.com"><i class="mdi mdi-instagram"></i></a></li>
                <li><a href="http://pinterest.com"><i class="mdi mdi-pinterest"></i></a></li>
            </ul>

        </aside>

        <!-- Categories widget-->
        <aside class="widget widget_categories">
            <div class="widget-title">Categories</div>
            <ul>
                <li><a href="#">Journey</a> (40)</li>
                <li><a href="#">Photography</a> (08)</li>
                <li><a href="#">Lifestyle</a> (11)</li>
                <li><a href="#">Food & Drinks</a> (21)</li>
            </ul>
        </aside>

        <!-- Recent entries widget-->
        <aside class="widget widget_recent_entries_custom">
            <div class="widget-title">Popular Posts</div>
            <ul>
                <li class="clearfix">
                    <div class="wi">
                        <a href="#"><img src="~/images/works/img1.jpg" alt="" class="img-fluid"></a>
                    </div>
                    <div class="wb"><a href="#">Beautiful Day With Friends..</a> <span class="post-date">Jun 15, 2017</span></div>
                </li>
                <li class="clearfix">
                    <div class="wi">
                        <a href="#"><img src="~/images/works/img2.jpg" alt="" class="img-fluid"></a>
                    </div>
                    <div class="wb"><a href="#">Nature valley with cooling..</a> <span class="post-date">Jun 10, 2017</span></div>
                </li>
                <li class="clearfix">
                    <div class="wi">
                        <a href="#"><img src="~/images/works/img3.jpg" alt="" class="img-fluid"></a>
                    </div>
                    <div class="wb"><a href="#">15 Best Healthy and Easy Salad..</a> <span class="post-date">Jun 8, 2017</span></div>
                </li>
            </ul>
        </aside>

        <!-- Text widget-->
        <aside class="widget">
            <div class="widget-title">Text Widget</div>

            <p class="text-muted text-widget-des">Exercitation photo booth stumptown tote bag Banksy, elit small batch freegan sed. Craft beer elit seitan exercitation, photo booth et 8-bit kale chips proident chillwave deep v laborum. Aliquip veniam delectus, Marfa eiusmod Pinterest in do umami readymade swag. </p>

        </aside>

        <!-- Archives widget-->
        <aside class="widget">
            <div class="widget-title">Archives</div>

            <ul>
                <li><a href="#">March 2017</a> (40)</li>
                <li><a href="#">April 2017</a> (08)</li>
                <li><a href="#">May 2017</a> (11)</li>
                <li><a href="#">Jun 2017</a> (21)</li>
            </ul>

        </aside>

        <!-- Tags widget-->
        <aside class="widget widget_tag_cloud">
            <div class="widget-title">Tags</div>
            <div class="tagcloud">
                <a href="#">logo</a>
                <a href="#">business</a>
                <a href="#">corporate</a>
                <a href="#">e-commerce</a>
                <a href="#">agency</a>
                <a href="#">responsive</a>
            </div>
        </aside>
    </div>
</div>
<!-- Sidebar end-->

BlogezyApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en"> 
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Responsive blog template">
    <meta name="author" content="Zoyothemes">
    <link rel="shortcut icon" href="images/favicon.ico">
    <title>Blogezy - Responsive Blog Template</title>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,600,700" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <!-- MENU CSS -->
    <link href="~/css/metismenu.min.css" rel="stylesheet" type="text/css" />
    <!-- MATERIALDESIGN ICON -->
    <link rel="stylesheet" type="text/css" href="~/css/materialdesignicons.min.css">
    <!-- CUSTOM STYLESHEET -->
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
    <link href="~/css/default.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <!-- Begin page -->
    <div id="wrapper">
        <!-- Top Bar Start -->
        <div class="topbar-mobile">
            <div class="logo">
                <a href="@Url.Action("Index", "Home")"><img src="~/images/logo.png" alt="" class="" style="height: 44px;"></a>
                <button class="button-menu-mobile">
                    <i class="mdi mdi-menu"></i>
                </button>
            </div>
        </div>
        <!-- Top Bar End -->
        <!-- ========== Left Sidebar Start ========== -->
        <div class="left side-menu">

            <div class="slimscroll-menu" id="remove-scroll">

                <div class="logo">
                    <a href="@Url.Action("Index", "Home")"><img src="~/images/logo.png" alt="" class="" style="height: 44px;"></a>
                    <p class="text-muted">Graduating from the halls of the University Of Western Sydney in late 2011. </p>
                </div>

                <!--- Sidemenu -->
                <div id="sidebar-menu">
                    <!-- Left Menu Start -->
                    <ul class="metismenu" id="side-menu">

                        <li>
                            <a href="index.html"><span> Home</span></a>
                        </li>

                        <li>
                            <a href="javascript: void(0);"><span> Features </span></a>
                            <ul class="nav-second-level" aria-expanded="false">
                                <li><a href="standard-post.html">Standard Post</a></li>
                                <li><a href="video-post.html">Video Post</a></li>
                                <li><a href="audio-post.html">Audio Post</a></li>
                                <li><a href="gallery-post.html">Gallery Post</a></li>
                                <li><a href="quote-post.html">Quote Post</a></li>
                                <li><a href="link-post.html">Link Post</a></li>
                                <li><a href="404.html">Error 404</a></li>
                            </ul>
                        </li>

                        <li>
                            <a href="javascript: void(0);"><span> Lifestyle </span></a>
                        </li>

                        <li>
                            <a href="javascript: void(0);"><span> Travel </span></a>
                        </li>

                        <li>
                            <a href="javascript: void(0);"><span> Music </span></a>
                        </li>

                        <li>
                            <a href="about.html">About</a>
                        </li>

                        <li>
                            <a href="contact.html">Contact</a>
                        </li>

                    </ul>

                    <div class="copyright-box">
                        <p>2017 © Blogezy. </p>
                    </div>

                </div>
                <!-- Sidebar -->
                <div class="clearfix"></div>

            </div>
            <!-- Sidebar -left -->

        </div>
        <!-- Left Sidebar End -->

        <div class="page-wrapper">
            <section>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="page-title">
                                <div class="row">
                                    <div class="col-md-9 col-xs-12">
                                        <h2><span>News and Stories</span></h2>

                                        <p class="subtitle text-muted">Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Proin gravida nibh vel velit auctor Aenean sollicitudin, adipisicing elit sed lorem quis bibendum auctor.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section class="mt-5 pb-5">
                <div class="container">

                    <div class="row">
                        <!-- Content-->
                        @RenderBody()
                        <!-- Content end-->
                    </div>
                </div>
                <!-- end container -->
            </section>
        </div>
    </div>
    <!-- js placed at the end of the document so the pages load faster -->
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.easing.min.js"></script>
    <script src="~/js/metisMenu.min.js"></script>
    <!--common script for all pages-->
    <script src="~/js/jquery.app.js"></script>
    <script>
        $.ajax({
            url: "https://reqres.in/api/users?page=4",
            method: "GET",
            success: function (res) { 
                setDate(res);
            },
            error: function (err) {
                console.log(err)
            }
        })

        function setDate(res) {
            const postTiles = document.querySelectorAll(".post-title");
            const images = document.querySelectorAll(".post-preview img");
            for (let i = 0; i < res.data.length;i++) {
                postTiles[i].innerHTML = `<a href="#">${res.data[i].first_name}</a>`
                images[i].src = res.data[i].avatar;
            }
        }
    </script>
</body> 
</html>